// Code generated by "admgencmd"; DO NOT EDIT.
// Sources: system.update.schedule.yaml, system.update.available.yaml, system.update.scan.yaml, system.update.status.yaml
// Options: no-shared=true
package mdmcommands

import "time"

const ScheduleOSUpdateRequestType = "ScheduleOSUpdate"

type UpdatesItem struct {
	ProductKey       *string `plist:",omitempty"`
	ProductVersion   *string `plist:",omitempty"`
	InstallAction    string
	MaxUserDeferrals *int    `plist:",omitempty"`
	Priority         *string `plist:",omitempty"`
}

// ScheduleOSUpdatePayload is the "inner" command-specific payload for the "ScheduleOSUpdate" Apple MDM command.
type ScheduleOSUpdatePayload struct {
	Updates                      []UpdatesItem
	RequestType                  string // must be set to "ScheduleOSUpdate"
	RequestRequiresNetworkTether *bool  `plist:",omitempty"`
}

// ScheduleOSUpdateCommand is the top-level structure for the "ScheduleOSUpdate" Apple MDM command.
type ScheduleOSUpdateCommand struct {
	Command     ScheduleOSUpdatePayload
	CommandUUID string
}

// GenericCommand creates a new generic command using the values of c
func (c *ScheduleOSUpdateCommand) GenericCommand() *GenericCommand {
	cmd := NewGenericCommand(c.Command.RequestType)
	cmd.CommandUUID = c.CommandUUID
	cmd.Command.RequestRequiresNetworkTether = c.Command.RequestRequiresNetworkTether
	return cmd
}

// NewScheduleOSUpdateCommand creates a new "ScheduleOSUpdate" Apple MDM command.
func NewScheduleOSUpdateCommand() *ScheduleOSUpdateCommand {
	return &ScheduleOSUpdateCommand{Command: ScheduleOSUpdatePayload{RequestType: ScheduleOSUpdateRequestType}}
}

func init() {
	// associate our Request Type to a function for creating a command of that type
	newCommandFuncs[ScheduleOSUpdateRequestType] = func() interface{} {
		return NewScheduleOSUpdateCommand()
	}
}

type ErrorChainItem struct {
	ANY interface{} // unknown type: <any>
}
type UpdateResultsItem struct {
	ProductKey    string
	InstallAction string
	Status        string
	ErrorChain    *[]ErrorChainItem `plist:",omitempty"`
}
type ScheduleOSUpdateResponse struct {
	UpdateResults []UpdateResultsItem
	GenericResponse
}

func init() {
	// associate our Request Type to a function for creating a response of that type
	newResponseFuncs[ScheduleOSUpdateRequestType] = func() interface{} {
		return new(ScheduleOSUpdateResponse)
	}
}

const AvailableOSUpdatesRequestType = "AvailableOSUpdates"

// AvailableOSUpdatesCommand is the top-level structure for the "AvailableOSUpdates" Apple MDM command.
type AvailableOSUpdatesCommand struct {
	Command     GenericCommandPayload
	CommandUUID string
}

// GenericCommand creates a new generic command using the values of c
func (c *AvailableOSUpdatesCommand) GenericCommand() *GenericCommand {
	cmd := NewGenericCommand(c.Command.RequestType)
	cmd.CommandUUID = c.CommandUUID
	cmd.Command.RequestRequiresNetworkTether = c.Command.RequestRequiresNetworkTether
	return cmd
}

// NewAvailableOSUpdatesCommand creates a new "AvailableOSUpdates" Apple MDM command.
func NewAvailableOSUpdatesCommand() *AvailableOSUpdatesCommand {
	return &AvailableOSUpdatesCommand{Command: GenericCommandPayload{RequestType: AvailableOSUpdatesRequestType}}
}

func init() {
	// associate our Request Type to a function for creating a command of that type
	newCommandFuncs[AvailableOSUpdatesRequestType] = func() interface{} {
		return NewAvailableOSUpdatesCommand()
	}
}

type AvailableOSUpdatesItem struct {
	ProductKey                 string
	HumanReadableName          string
	HumanReadableNameLocale    string
	MetadataURL                string
	ProductName                string
	Version                    string
	Build                      string
	DownloadSize               int
	InstallSize                int
	AppIdentifiersToClose      []string
	IsCritical                 *bool      `plist:",omitempty"`
	IsConfigDataUpdate         *bool      `plist:",omitempty"`
	IsFirmwareUpdate           *bool      `plist:",omitempty"`
	IsMajorOSUpdate            *bool      `plist:",omitempty"`
	RestartRequired            *bool      `plist:",omitempty"`
	AllowsInstallLater         *bool      `plist:",omitempty"`
	DeferredUntil              *time.Time `plist:",omitempty"`
	RequiresBootstrapToken     *bool      `plist:",omitempty"`
	IsSecurityResponse         bool
	SupplementalBuildVersion   *string `plist:",omitempty"`
	SupplementalOSVersionExtra *string `plist:",omitempty"`
}
type AvailableOSUpdatesResponse struct {
	AvailableOSUpdates []AvailableOSUpdatesItem
	GenericResponse
}

func init() {
	// associate our Request Type to a function for creating a response of that type
	newResponseFuncs[AvailableOSUpdatesRequestType] = func() interface{} {
		return new(AvailableOSUpdatesResponse)
	}
}

const ScheduleOSUpdateScanRequestType = "ScheduleOSUpdateScan"

// ScheduleOSUpdateScanPayload is the "inner" command-specific payload for the "ScheduleOSUpdateScan" Apple MDM command.
type ScheduleOSUpdateScanPayload struct {
	Force                        *bool  `plist:",omitempty"`
	RequestType                  string // must be set to "ScheduleOSUpdateScan"
	RequestRequiresNetworkTether *bool  `plist:",omitempty"`
}

// ScheduleOSUpdateScanCommand is the top-level structure for the "ScheduleOSUpdateScan" Apple MDM command.
type ScheduleOSUpdateScanCommand struct {
	Command     ScheduleOSUpdateScanPayload
	CommandUUID string
}

// GenericCommand creates a new generic command using the values of c
func (c *ScheduleOSUpdateScanCommand) GenericCommand() *GenericCommand {
	cmd := NewGenericCommand(c.Command.RequestType)
	cmd.CommandUUID = c.CommandUUID
	cmd.Command.RequestRequiresNetworkTether = c.Command.RequestRequiresNetworkTether
	return cmd
}

// NewScheduleOSUpdateScanCommand creates a new "ScheduleOSUpdateScan" Apple MDM command.
func NewScheduleOSUpdateScanCommand() *ScheduleOSUpdateScanCommand {
	return &ScheduleOSUpdateScanCommand{Command: ScheduleOSUpdateScanPayload{RequestType: ScheduleOSUpdateScanRequestType}}
}

func init() {
	// associate our Request Type to a function for creating a command of that type
	newCommandFuncs[ScheduleOSUpdateScanRequestType] = func() interface{} {
		return NewScheduleOSUpdateScanCommand()
	}
}

type ScheduleOSUpdateScanResponse struct {
	ScanInitiated bool
	GenericResponse
}

func init() {
	// associate our Request Type to a function for creating a response of that type
	newResponseFuncs[ScheduleOSUpdateScanRequestType] = func() interface{} {
		return new(ScheduleOSUpdateScanResponse)
	}
}

const OSUpdateStatusRequestType = "OSUpdateStatus"

// OSUpdateStatusCommand is the top-level structure for the "OSUpdateStatus" Apple MDM command.
type OSUpdateStatusCommand struct {
	Command     GenericCommandPayload
	CommandUUID string
}

// GenericCommand creates a new generic command using the values of c
func (c *OSUpdateStatusCommand) GenericCommand() *GenericCommand {
	cmd := NewGenericCommand(c.Command.RequestType)
	cmd.CommandUUID = c.CommandUUID
	cmd.Command.RequestRequiresNetworkTether = c.Command.RequestRequiresNetworkTether
	return cmd
}

// NewOSUpdateStatusCommand creates a new "OSUpdateStatus" Apple MDM command.
func NewOSUpdateStatusCommand() *OSUpdateStatusCommand {
	return &OSUpdateStatusCommand{Command: GenericCommandPayload{RequestType: OSUpdateStatusRequestType}}
}

func init() {
	// associate our Request Type to a function for creating a command of that type
	newCommandFuncs[OSUpdateStatusRequestType] = func() interface{} {
		return NewOSUpdateStatusCommand()
	}
}

type OSUpdateStatusItem struct {
	ProductKey              string
	IsDownloaded            bool
	DownloadPercentComplete float64
	Status                  string
	MaxDeferrals            *int         `plist:",omitempty"`
	DeferralsRemaining      *int         `plist:",omitempty"`
	NextScheduledInstall    *time.Time   `plist:",omitempty"`
	PastNotifications       *[]time.Time `plist:",omitempty"`
}
type OSUpdateStatusResponse struct {
	OSUpdateStatus []OSUpdateStatusItem
	GenericResponse
}

func init() {
	// associate our Request Type to a function for creating a response of that type
	newResponseFuncs[OSUpdateStatusRequestType] = func() interface{} {
		return new(OSUpdateStatusResponse)
	}
}
