// Code generated by "admgencmd"; DO NOT EDIT.
package mdmcommands

const InstallMediaRequestType = "InstallMedia"

type InstallMediaPayload struct {
	ITunesStoreID                *int    `plist:"iTunesStoreID,omitempty"`
	MediaURL                     *string `plist:",omitempty"`
	MediaType                    string
	PersistentID                 *string `plist:",omitempty"`
	Kind                         *string `plist:",omitempty"`
	Version                      *string `plist:",omitempty"`
	Author                       *string `plist:",omitempty"`
	Title                        *string `plist:",omitempty"`
	RequestType                  string  // must be set to "InstallMedia"
	RequestRequiresNetworkTether *bool   `plist:",omitempty"`
}
type InstallMediaCommand struct {
	Command     InstallMediaPayload
	CommandUUID string
}

// NewInstallMediaCommand creates a new "InstallMedia" Apple MDM command.
func NewInstallMediaCommand() *InstallMediaCommand {
	return &InstallMediaCommand{Command: InstallMediaPayload{RequestType: InstallMediaRequestType}}
}

type InstallMediaResponse struct {
	ITunesStoreID   *int    `plist:"iTunesStoreID,omitempty"`
	MediaURL        *string `plist:",omitempty"`
	PersistentID    *string `plist:",omitempty"`
	MediaType       *string `plist:",omitempty"`
	State           *string `plist:",omitempty"`
	RejectionReason *string `plist:",omitempty"`
	CommandUUID     string
	Status          string
}
