// Code generated by "admgencmd"; DO NOT EDIT.
// Sources: remotedesktop.enable.yaml, remotedesktop.disable.yaml
// Options: no-shared=true
package mdmcommands

const EnableRemoteDesktopRequestType = "EnableRemoteDesktop"

// EnableRemoteDesktopCommand is the top-level structure for the "EnableRemoteDesktop" Apple MDM command.
type EnableRemoteDesktopCommand struct {
	Command     GenericCommandPayload
	CommandUUID string
}

// GenericCommand creates a new generic command using the values of c
func (c *EnableRemoteDesktopCommand) GenericCommand() *GenericCommand {
	cmd := NewGenericCommand(c.Command.RequestType)
	cmd.CommandUUID = c.CommandUUID
	cmd.Command.RequestRequiresNetworkTether = c.Command.RequestRequiresNetworkTether
	return cmd
}

// NewEnableRemoteDesktopCommand creates a new "EnableRemoteDesktop" Apple MDM command.
func NewEnableRemoteDesktopCommand() *EnableRemoteDesktopCommand {
	return &EnableRemoteDesktopCommand{Command: GenericCommandPayload{RequestType: EnableRemoteDesktopRequestType}}
}

func init() {
	// associate our Request Type to a function for creating a command of that type
	newCommandFuncs[EnableRemoteDesktopRequestType] = func() interface{} {
		return NewEnableRemoteDesktopCommand()
	}
}

type EnableRemoteDesktopResponse struct {
	GenericResponse
}

func init() {
	// associate our Request Type to a function for creating a response of that type
	newResponseFuncs[EnableRemoteDesktopRequestType] = func() interface{} {
		return new(EnableRemoteDesktopResponse)
	}
}

const DisableRemoteDesktopRequestType = "DisableRemoteDesktop"

// DisableRemoteDesktopCommand is the top-level structure for the "DisableRemoteDesktop" Apple MDM command.
type DisableRemoteDesktopCommand struct {
	Command     GenericCommandPayload
	CommandUUID string
}

// GenericCommand creates a new generic command using the values of c
func (c *DisableRemoteDesktopCommand) GenericCommand() *GenericCommand {
	cmd := NewGenericCommand(c.Command.RequestType)
	cmd.CommandUUID = c.CommandUUID
	cmd.Command.RequestRequiresNetworkTether = c.Command.RequestRequiresNetworkTether
	return cmd
}

// NewDisableRemoteDesktopCommand creates a new "DisableRemoteDesktop" Apple MDM command.
func NewDisableRemoteDesktopCommand() *DisableRemoteDesktopCommand {
	return &DisableRemoteDesktopCommand{Command: GenericCommandPayload{RequestType: DisableRemoteDesktopRequestType}}
}

func init() {
	// associate our Request Type to a function for creating a command of that type
	newCommandFuncs[DisableRemoteDesktopRequestType] = func() interface{} {
		return NewDisableRemoteDesktopCommand()
	}
}

type DisableRemoteDesktopResponse struct {
	GenericResponse
}

func init() {
	// associate our Request Type to a function for creating a response of that type
	newResponseFuncs[DisableRemoteDesktopRequestType] = func() interface{} {
		return new(DisableRemoteDesktopResponse)
	}
}
