package mdmcommands

//go:generate admgencmd -pkg mdmcommands -o shared.go
//go:generate admgencmd -pkg mdmcommands -no-shared -o cmd_media.go device-management/mdm/commands/media.install.yaml device-management/mdm/commands/media.remove.yaml device-management/mdm/commands/media.managed.list.yaml
//go:generate admgencmd -pkg mdmcommands -no-shared -o cmd_information.go device-management/mdm/commands/information.device.yaml device-management/mdm/commands/information.security.yaml
//go:generate admgencmd -pkg mdmcommands -no-shared -o cmd_profile.go device-management/mdm/commands/profile.install.yaml device-management/mdm/commands/profile.remove.yaml device-management/mdm/commands/profile.list.yaml device-management/mdm/commands/profile.provisioning.install.yaml device-management/mdm/commands/profile.provisioning.remove.yaml device-management/mdm/commands/profile.provisioning.list.yaml
//go:generate admgencmd -pkg mdmcommands -no-shared -o cmd_remotedesktop.go device-management/mdm/commands/remotedesktop.enable.yaml device-management/mdm/commands/remotedesktop.disable.yaml
//go:generate admgencmd -pkg mdmcommands -no-shared -o cmd_device_actions.go device-management/mdm/commands/device.shutdown.yaml device-management/mdm/commands/device.restart.yaml device-management/mdm/commands/device.configured.yaml device-management/mdm/commands/mirroring.stop.yaml device-management/mdm/commands/mirroring.request.yaml device-management/mdm/commands/device.erase.yaml device-management/mdm/commands/device.lostmode.enable.yaml device-management/mdm/commands/device.lostmode.disable.yaml device-management/mdm/commands/device.lock.yaml
//go:generate admgencmd -pkg mdmcommands -no-shared -o cmd_update.go device-management/mdm/commands/system.update.schedule.yaml device-management/mdm/commands/system.update.available.yaml device-management/mdm/commands/system.update.scan.yaml device-management/mdm/commands/system.update.status.yaml
//go:generate admgencmd -pkg mdmcommands -no-shared -o cmd_user.go device-management/mdm/commands/user.delete.yaml device-management/mdm/commands/user.list.yaml device-management/mdm/commands/user.logout.yaml device-management/mdm/commands/user.unlock.yaml
