package mdmcommands

//go:generate admgencmd -pkg mdmcommands -o shared.go
//go:generate admgencmd -pkg mdmcommands -no-shared -o cmd_media.go device-management/mdm/commands/media.install.yaml device-management/mdm/commands/media.remove.yaml device-management/mdm/commands/media.managed.list.yaml
//go:generate admgencmd -pkg mdmcommands -no-shared -o cmd_information.go device-management/mdm/commands/information.device.yaml device-management/mdm/commands/information.security.yaml device-management/mdm/commands/certificate.list.yaml
//go:generate admgencmd -pkg mdmcommands -no-shared -o cmd_profile.go device-management/mdm/commands/profile.install.yaml device-management/mdm/commands/profile.remove.yaml device-management/mdm/commands/profile.list.yaml device-management/mdm/commands/profile.provisioning.install.yaml device-management/mdm/commands/profile.provisioning.remove.yaml device-management/mdm/commands/profile.provisioning.list.yaml
//go:generate admgencmd -pkg mdmcommands -no-shared -o cmd_remotedesktop.go device-management/mdm/commands/remotedesktop.enable.yaml device-management/mdm/commands/remotedesktop.disable.yaml
//go:generate admgencmd -pkg mdmcommands -no-shared -o cmd_mirroring.go device-management/mdm/commands/mirroring.stop.yaml device-management/mdm/commands/mirroring.request.yaml
//go:generate admgencmd -pkg mdmcommands -no-shared -o cmd_device.go device-management/mdm/commands/device.shutdown.yaml device-management/mdm/commands/device.restart.yaml device-management/mdm/commands/device.configured.yaml device-management/mdm/commands/device.erase.yaml device-management/mdm/commands/device.lostmode.enable.yaml device-management/mdm/commands/device.lostmode.disable.yaml device-management/mdm/commands/device.lostmode.location.yaml device-management/mdm/commands/device.lostmode.playsound.yaml device-management/mdm/commands/device.restrictions.clearpassword.yaml device-management/mdm/commands/device.lock.yaml device-management/mdm/commands/device.esim.yaml device-management/mdm/commands/device.activationlock.bypasscode.yaml device-management/mdm/commands/device.activationlock.clearbypasscode.yaml device-management/mdm/commands/declarativemanagement.yaml device-management/mdm/commands/rotate.file.vault.key.yaml
//go:generate admgencmd -pkg mdmcommands -no-shared -o cmd_update.go device-management/mdm/commands/system.update.schedule.yaml device-management/mdm/commands/system.update.available.yaml device-management/mdm/commands/system.update.scan.yaml device-management/mdm/commands/system.update.status.yaml
//go:generate admgencmd -pkg mdmcommands -no-shared -o cmd_user.go device-management/mdm/commands/user.delete.yaml device-management/mdm/commands/user.list.yaml device-management/mdm/commands/user.logout.yaml device-management/mdm/commands/user.unlock.yaml device-management/mdm/commands/set.auto.admin.password.yaml device-management/mdm/commands/account.configuration.yaml
//go:generate admgencmd -pkg mdmcommands -no-shared -o cmd_lom.go device-management/mdm/commands/lom.devicerequest.yaml device-management/mdm/commands/lom.setuprequest.yaml
//go:generate admgencmd -pkg mdmcommands -no-shared -o cmd_passcode.go device-management/mdm/commands/passcode.unlocktoken.yaml device-management/mdm/commands/passcode.recovery.set.yaml device-management/mdm/commands/passcode.clear.yaml device-management/mdm/commands/passcode.firmware.verify.yaml device-management/mdm/commands/passcode.recovery.verify.yaml device-management/mdm/commands/passcode.firmware.set.yaml
//go:generate admgencmd -pkg mdmcommands -no-shared -o cmd_apps.go device-management/mdm/commands/application.remove.yaml device-management/mdm/commands/application.install.yaml device-management/mdm/commands/application.install.enterprise.yaml device-management/mdm/commands/application.extensions.mappings.yaml device-management/mdm/commands/application.validate.yaml device-management/mdm/commands/application.installed.list.yaml device-management/mdm/commands/application.redemptioncode.yaml device-management/mdm/commands/application.invitetoprogram.yaml
