// Code generated by "admgencmd"; DO NOT EDIT.
package mdmcommands

// GenericCommandPayload is the "inner" generic payload for Apple MDM commands.
type GenericCommandPayload struct {
	RequestType                  string // must be set to MDM command name
	RequestRequiresNetworkTether *bool  `plist:",omitempty"`
}

// GenericCommand represents a generic command.
type GenericCommand struct {
	CommandUUID string
	Command     GenericCommandPayload
}

// NewGenericCommand creates a new generic Apple MDM command.
func NewGenericCommand(requestType string) *GenericCommand {
	return &GenericCommand{Command: GenericCommandPayload{RequestType: requestType}}
}
